name: NGui
version: '${version}'

main: io.neris.NGui.NGui
api-version: '26.2'
load: POSTWORLD

commands:
  menu:
    description: Команда под меню
    usage: /menu

permissions:
  ngui.help:
    default: op

  ngui.test:
    default: op

  ngui.closeall:
    default: op

  ngui.closefor:
    default: op
